---
title: "Blank Check March Madness: Main Feed"
output: 
  html_document:
    keep_md: true
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(tidyverse)
purrr::walk(list.files("./R", full.names = TRUE), source)
theme_set(theme_minimal())
```

```{r}
vote_data <- read_csv("data/votes-mainfeed-2020.csv")
patreon_data <- read_csv("data/votes-patreon-2020.csv")
bc_colors <- list(purple = "#715280", blue = "#5B86BF", green = "#6D8F6C", bagel = "#D3984F", gold = "#F9CE5E")
```

```{r}
matchup_data <- make_matchup_data(vote_data)
matchups_wvl <- matchup_data %>% 
  filter(votes1 > votes2) %>% 
  mutate(matchup = paste(director1, director2, sep = " vs "))
```

```{r, fig.width = 10}
# patreon
patreon_matchups <- make_matchup_data(patreon_data,"patreon")
matchups_wvl_patreon <- patreon_matchups %>% 
  filter(votes1 > votes2) %>% 
  mutate(matchup = paste(franchise1, franchise2, sep = " vs "))

combined_matchups <- select(matchups_wvl, -c(director1, director2)) %>% 
  mutate(feed = "main") %>% 
  bind_rows(select(matchups_wvl_patreon, -c(franchise1, franchise2)) %>% mutate(feed = "patreon")) %>% 
  mutate(
    margin = votes1 - votes2,
    percent = 100 * margin / total_votes,
    matchup = str_replace_all(matchup, "The Original Series", "TOS")
  )

ggplot(combined_matchups, aes(forcats::fct_reorder(matchup, total_votes), total_votes, fill = as.factor(round))) +
  geom_bar(stat = "identity") + 
  scale_fill_manual(values = as.character(bc_colors)) +
  coord_flip() + 
  facet_wrap(~feed, scales = "free") +
  labs(
    title = "Total Votes by Matchup",
    subtitle = "winner named first",
    x = "Matchup",
    y = "Total Votes",
    fill = "Round"
  )

combined_matchups %>% 
  ggplot(aes(forcats::fct_reorder(matchup, margin), margin, fill = as.factor(round))) + 
  geom_bar(stat = "identity") +
  scale_fill_manual(values = as.character(bc_colors)) +
  coord_flip() + 
  facet_wrap(~feed, scales = "free_y") +
  labs(
    title = "Margin of Victory",
    subtitle = "winner named first",
    x = "Matchup",
    y = "Votes",
    fill = "Round"
  )
```

```{r}
award_data <- read_csv("data/oscar-razzie.csv")
matchups_wvl %>% 
  left_join(award_data, by = c("director1" = "director")) %>% 
  ggplot(aes(forcats::fct_reorder(matchup, total_votes), total_votes, fill = award)) + 
  geom_bar(stat = "identity") + 
  # scale_fill_manual(values = ) +
  scale_fill_manual(values = c(bc_colors$gold, bc_colors$purple)) +
  coord_flip() + 
  labs(
    title = "Total Votes by Matchup",
    subtitle = "winner named first",
    x = "Matchup",
    y = "Total Votes",
    fill = "Round"
  )
```

```{r}
final_four_directors <- matchups_wvl %>% 
  filter(round == 3) %>% 
  magrittr::use_series(director1)

final_four <- matchups_wvl %>% 
  filter(director1 %in% final_four_directors)

final_four %>% 
  inner_join(award_data, by = c("director1" = "director")) %>% 
  # filter(award == "oscar") %>% 
  ggplot(aes(forcats::fct_reorder(matchup, votes2), votes2, fill = as.factor(round))) + 
  geom_bar(stat = 'identity') +
  coord_flip() +
  scale_fill_manual(values = as.character(bc_colors)) +
  labs(
    title = "Winning Votes in each Round",
    subtitle = "Robert Zemeckis and Bong Joon-ho",
    x = "matchup",
    y = "winning votes",
    fill = "round"
  )
```

Votes in previous round aren't a good predictor for votes.  

```{r}
# votes in previous round predict winner?
previous_round <- matchup_data %>% 
  mutate(previous_round = round - 1) %>% 
  inner_join(., ., by = c("director1" = "director1", "previous_round" = "round")) 

previous_round %>% 
  mutate(winner = votes1.x > votes2.x) %>% 
  ggplot(aes(votes1.y, votes1.x, color = winner)) + 
  geom_point() +
  labs(
    x = "votes in previous round",
    y = "votes in round"
  ) +
  geom_smooth(method = "lm")
```

Hypothetical Margin of previous round is not a good predictor of current margin.  

```{r}
# vote differential of previous round predict differential?
previous_round %>% 
  select(round, director1, director2 = director2.x, votes1 = votes1.x, votes2 = votes2.x, votes1_prev = votes1.y, previous_round) %>% 
  inner_join(select(matchup_data, round, director1, votes2_prev = votes1), by = c("director2" = "director1", "previous_round" = "round")) %>% 
  select(-previous_round) %>% 
  mutate(margin = votes1 - votes2, prev_margin = votes1_prev - votes2_prev) %>%
  ggplot(aes(prev_margin, margin)) + 
  geom_point() + 
  geom_smooth(method = "lm")

# both weak
```

Likely need to account for the matchup, not just general preference.  

```{r}
select(matchups_wvl, matchup, round, winner = director1, loser = director2, winning_votes = votes1, losing_votes = votes2, total_votes) %>% 
  DT::datatable()
```

